print("Ahmed")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("What are you doing")
print("Ahmed nawazkhan ")
print("Ahmed nawazkhan ")
print("Ahmed nawazkhan ")
print("I am teaching Python")
print("I am teaching Python")
print("I am teaching Python")